/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package activitylogsmanagement.app

import activitylogsmanagement.app.di.ConfigModule
import activitylogsmanagement.app.di.DaggerAppComponent
import activitylogsmanagement.app.helper.AppContext


fun main(args: Array<String>) {


    AppContext.init(args)

    var component = DaggerAppComponent.builder().configModule(ConfigModule()).build()

    component.httpServer().start();

    component.activityLogConsumer().startConsuming();

    println("Server created successfully! and consumer started consuming");

}
